sonata_media:
  class:
    media: App\Entity\SonataMediaMedia
  resource: "@SonataMediaBundle/Resources/config/routing/media.xml"
  prefix: /media
  db_driver: doctrine_orm
  default_context: default
  contexts:
    default: # the default context is mandatory
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file
      formats:
        small: { width: 100, quality: 70 }
        big: { width: 500, quality: 70 }
  cdn:
    server:
      path: /uploads/media
  filesystem:
    local:
      directory: "%kernel.project_dir%/public/uploads/media"
      create: false
